# Generated by Django 5.1 on 2024-08-28 00:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='like',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', '학생'), ('teacher', '선생님'), ('admin', '관리자')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_uid',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, unique=True),
        ),
    ]
