# Generated by Django 5.1 on 2024-09-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubapplication',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.DeleteModel(
            name='ClubContent',
        ),
    ]
